import path from 'node:path';
import type { Express } from 'express';
import {
  createEnforceWorkspaceProjectMutation,
} from './index.js';
import {
  createAuthorizeProjectRequest,
  type AuthorizeProjectRequest,
} from '../../collab/project-request-authority.js';
import { ensureCurrentProjectFileVersion } from '../../project-file-versions.js';
import { ensureProjectSubdir, sanitizeName } from '../../projects.js';
import type { RouteDeps } from '../../server-context.js';

/**
 * Chunked project upload. Large (> CHUNK_THRESHOLD backend mirror) files are
 * PUT as many small octet-stream chunks so each request stays far below the
 * 100MB edge/Cloudflare request-body cap, then assembled into the project
 * directory on complete. Same response shape as POST /api/projects/:id/upload
 * so the composer treats both paths identically.
 *
 * Staging lives under RUNTIME_DATA_DIR/upload-staging (daemon data-root
 * contract: derived from the resolved daemon data root, never cwd-relative).
 */

const MAX_TOTAL_CHUNKS = 1024;
const STAGING_MAX_AGE_MS = 6 * 60 * 60 * 1000;
const STAGING_SWEEP_INTERVAL_MS = 10 * 60 * 1000;
// uploadId is generated by the web client from safe charset; the regex is the
// server-side guarantee that it is a single safe path segment (no traversal).
const UPLOAD_ID_PATTERN = /^[A-Za-z0-9_-]{8,64}$/;

function headerString(value: unknown): string {
  return typeof value === 'string'
    ? value
    : Array.isArray(value) && typeof value[0] === 'string' ? value[0] : '';
}

export interface RegisterProjectChunkUploadRoutesDeps
  extends RouteDeps<'db' | 'http' | 'node' | 'paths' | 'projectStore' | 'projectFiles'> {
  authorizeProjectRequest?: AuthorizeProjectRequest;
  isProjectUnmaterializedPlaceholder?: (projectId: string) => boolean;
}

interface UploadMeta {
  totalChunks: number;
  name: string;
  dir: string;
}

let lastSweepAt = 0;

function stagingDirFor(root: string, uploadId: string) {
  return path.join(root, uploadId);
}

async function readUploadMeta(
  fs: any,
  stageDir: string,
): Promise<UploadMeta | null> {
  try {
    const raw = await fs.promises.readFile(path.join(stageDir, 'meta.json'), 'utf8');
    const parsed = JSON.parse(raw);
    if (
      !Number.isInteger(parsed?.totalChunks)
      || parsed.totalChunks < 1
      || parsed.totalChunks > MAX_TOTAL_CHUNKS
      || typeof parsed?.name !== 'string'
      || typeof parsed?.dir !== 'string'
    ) return null;
    return parsed;
  } catch {
    return null;
  }
}

async function writeUploadMeta(fs: any, stageDir: string, meta: UploadMeta) {
  await fs.promises.writeFile(path.join(stageDir, 'meta.json'), JSON.stringify(meta), 'utf8');
}

async function receivedChunkIndexes(fs: any, stageDir: string): Promise<number[]> {
  const entries = await fs.promises.readdir(stageDir);
  return entries
    .filter((e: string) => /^\d+$/.test(e))
    .map((e: string) => Number.parseInt(e, 10))
    .filter((n: number) => Number.isInteger(n) && n >= 0)
    .sort((a: number, b: number) => a - b);
}

async function sweepStaleStagingDirs(fs: any, stagingRoot: string) {
  const now = Date.now();
  if (now - lastSweepAt < STAGING_SWEEP_INTERVAL_MS) return;
  lastSweepAt = now;
  let entries: string[];
  try {
    entries = await fs.promises.readdir(stagingRoot);
  } catch {
    return;
  }
  for (const entry of entries) {
    if (!UPLOAD_ID_PATTERN.test(entry)) continue;
    const dir = path.join(stagingRoot, entry);
    try {
      const st = await fs.promises.stat(dir);
      if (now - st.mtimeMs > STAGING_MAX_AGE_MS) {
        await fs.promises.rm(dir, { recursive: true, force: true });
      }
    } catch {
      // vanished mid-sweep — fine
    }
  }
}

export function registerProjectChunkUploadRoutes(
  app: Express,
  ctx: RegisterProjectChunkUploadRoutesDeps,
) {
  const { db } = ctx;
  const { sendApiError } = ctx.http;
  const { fs } = ctx.node;
  const { PROJECTS_DIR, RUNTIME_DATA_DIR } = ctx.paths;
  const stagingRoot = path.join(RUNTIME_DATA_DIR, 'upload-staging');
  const { getProject, getWorkspaceProject, getWorkspaceProjectByProjectId } = ctx.projectStore;
  const { writeProjectFile, readProjectFile } = ctx.projectFiles;
  const authorizeProjectRequest =
    ctx.authorizeProjectRequest ??
    createAuthorizeProjectRequest({
      db,
      getWorkspaceProject,
      getWorkspaceProjectByProjectId,
      ...(ctx.isProjectUnmaterializedPlaceholder
        ? {
            isProjectUnmaterializedPlaceholder: (_db: unknown, projectId: string) =>
              ctx.isProjectUnmaterializedPlaceholder?.(projectId) ?? false,
          }
        : {}),
      sendApiError,
    });
  const enforceWorkspaceProjectMutation = createEnforceWorkspaceProjectMutation(
    undefined,
    undefined,
    authorizeProjectRequest,
  );

  const gateWrite = async (req: any, res: any, projectId: string): Promise<boolean> =>
    enforceWorkspaceProjectMutation(
      req,
      res,
      sendApiError,
      getWorkspaceProject,
      getWorkspaceProjectByProjectId,
      db,
      projectId,
      'writeFiles',
    );

  app.put(
    '/api/projects/:id/upload/:uploadId/chunk/:index',
    async (req, res) => {
      try {
        const { uploadId, index } = req.params;
        if (!UPLOAD_ID_PATTERN.test(uploadId)) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid upload id');
        }
        const chunkIndex = Number.parseInt(index, 10);
        if (!Number.isInteger(chunkIndex) || String(chunkIndex) !== index || chunkIndex < 0) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid chunk index');
        }
        const totalChunks = Number.parseInt(headerString(req.headers['x-total-chunks']), 10);
        if (!Number.isInteger(totalChunks) || totalChunks < 1 || totalChunks > MAX_TOTAL_CHUNKS) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid total chunks');
        }
        if (chunkIndex >= totalChunks) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'chunk index out of range');
        }
        const body = Buffer.isBuffer(req.body) ? req.body : null;
        if (!body || body.length === 0) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'chunk body required');
        }
        if (!await gateWrite(req, res, req.params.id)) return;
        const stageDir = stagingDirFor(stagingRoot, uploadId);
        await fs.promises.mkdir(stageDir, { recursive: true });
        const meta = await readUploadMeta(fs, stageDir);
        if (meta) {
          if (meta.totalChunks !== totalChunks) {
            return sendApiError(res, 400, 'BAD_REQUEST', 'total chunks does not match previous upload');
          }
        } else {
          const decodedName = decodeURIComponent(headerString(req.headers['x-file-name']));
          if (!decodedName) return sendApiError(res, 400, 'BAD_REQUEST', 'x-file-name header required');
          const dirRaw = headerString(req.headers['x-dir']);
          const dir = dirRaw ? decodeURIComponent(dirRaw) : '';
          // First chunk stamps the upload meta; later chunk PUTs must agree.
          await writeUploadMeta(fs, stageDir, {
            totalChunks,
            name: sanitizeName(decodedName),
            dir,
          });
        }
        await fs.promises.writeFile(path.join(stageDir, String(chunkIndex)), body);
        sweepStaleStagingDirs(fs, stagingRoot).catch(() => {});
        res.json({ ok: true });
      } catch {
        sendApiError(res, 500, 'INTERNAL_ERROR', 'chunk upload failed');
      }
    },
  );

  app.post(
    '/api/projects/:id/upload/:uploadId/complete',
    async (req, res) => {
      try {
        const { uploadId } = req.params;
        if (!UPLOAD_ID_PATTERN.test(uploadId)) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid upload id');
        }
        if (!await gateWrite(req, res, req.params.id)) return;
        const stageDir = stagingDirFor(stagingRoot, uploadId);
        const meta = await readUploadMeta(fs, stageDir);
        if (!meta) {
          return sendApiError(res, 404, 'UPLOAD_NOT_FOUND', 'upload not found');
        }
        const declared = Number.isInteger(req.body?.totalChunks) ? req.body.totalChunks : null;
        if (declared !== null && declared !== meta.totalChunks) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'total chunks does not match upload');
        }
        const project = getProject(db, req.params.id);
        if (!project) {
          return sendApiError(res, 404, 'PROJECT_NOT_FOUND', 'project not found');
        }
        const received = await receivedChunkIndexes(fs, stageDir);
        if (received.length !== meta.totalChunks
          || (received.length > 0 && received[received.length - 1] !== meta.totalChunks - 1)) {
          return sendApiError(res, 400, 'INCOMPLETE_UPLOAD', 'not all chunks received');
        }
        const chunks = await Promise.all(
          received.map((i) => fs.promises.readFile(path.join(stageDir, String(i)))),
        );
        const buffer = Buffer.concat(chunks);
        const { relDir } = await ensureProjectSubdir(PROJECTS_DIR, req.params.id, meta.dir, project.metadata);
        const finalName = relDir ? `${relDir}/${meta.name}` : meta.name;
        const saved = await writeProjectFile(
          PROJECTS_DIR,
          project.id,
          finalName,
          buffer,
          {},
          project.metadata,
        );
        if (/\.html?$/i.test(finalName)) {
          try {
            const savedFile = await readProjectFile(
              PROJECTS_DIR,
              project.id,
              finalName,
              project.metadata,
            );
            await ensureCurrentProjectFileVersion(
              PROJECTS_DIR,
              project.id,
              savedFile.name,
              savedFile.buffer.toString('utf8'),
              { source: 'manual', promptSource: 'manual' },
              project.metadata,
            );
          } catch {
            // Same best-effort posture as the direct /upload route.
          }
        }
        await fs.promises.rm(stageDir, { recursive: true, force: true });
        /** @type {import('@open-design/contracts').UploadProjectFilesResponse} */
        const out = {
          name: saved.name,
          path: saved.path,
          size: saved.size,
          mtime: saved.mtime,
          originalName: meta.name,
        };
        res.json({ files: [out] });
      } catch {
        sendApiError(res, 500, 'INTERNAL_ERROR', 'upload failed');
      }
    },
  );

  app.delete(
    '/api/projects/:id/upload/:uploadId',
    async (req, res) => {
      try {
        const { uploadId } = req.params;
        if (!UPLOAD_ID_PATTERN.test(uploadId)) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid upload id');
        }
        if (!await gateWrite(req, res, req.params.id)) return;
        await fs.promises.rm(stagingDirFor(stagingRoot, uploadId), {
          recursive: true,
          force: true,
        });
        res.json({ ok: true });
      } catch {
        sendApiError(res, 500, 'INTERNAL_ERROR', 'abort failed');
      }
    },
  );

  app.get(
    '/api/projects/:id/upload/:uploadId',
    async (req, res) => {
      try {
        const { uploadId } = req.params;
        if (!UPLOAD_ID_PATTERN.test(uploadId)) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid upload id');
        }
        if (!authorizeProjectRequest(req, res, req.params.id, { mode: 'write', capability: 'writeFiles' })) {
          return;
        }
        const stageDir = stagingDirFor(stagingRoot, uploadId);
        const meta = await readUploadMeta(fs, stageDir);
        if (!meta) {
          return sendApiError(res, 404, 'UPLOAD_NOT_FOUND', 'upload not found');
        }
        const received = await receivedChunkIndexes(fs, stageDir);
        res.json({ received, totalChunks: meta.totalChunks });
      } catch {
        sendApiError(res, 500, 'INTERNAL_ERROR', 'status failed');
      }
    },
  );
}
