import path from 'node:path';
import type { Express } from 'express';
import { PROJECT_UPLOAD_MAX_BYTES } from '@open-design/contracts';
import {
  createEnforceWorkspaceProjectMutation,
} from './index.js';
import {
  createAuthorizeProjectRequest,
  type AuthorizeProjectRequest,
} from '../../collab/project-request-authority.js';
import { ensureCurrentProjectFileVersion } from '../../project-file-versions.js';
import { ensureProjectSubdir, sanitizeName } from '../../projects.js';
import type { RouteDeps } from '../../server-context.js';

/**
 * Chunked project upload. Large (> CHUNK_THRESHOLD backend mirror) files are
 * PUT as many small octet-stream chunks so each request stays far below the
 * 100MB edge/Cloudflare request-body cap, then assembled into the project
 * directory on complete. Same response shape as POST /api/projects/:id/upload
 * so the composer treats both paths identically.
 *
 * Assembly appends chunk files to a staging file one at a time and then moves
 * it into the project dir, so peak heap stays around one chunk regardless of
 * the assembled file size. The total upload size is enforced server-side
 * against PROJECT_UPLOAD_MAX_BYTES (or the OD_MAX_UPLOAD_MB override) via
 * cumulative per-chunk byte tracking in meta.json.
 *
 * Staging lives under RUNTIME_DATA_DIR/upload-staging (daemon data-root
 * contract: derived from the resolved daemon data root, never cwd-relative).
 */

const MAX_TOTAL_CHUNKS = 1024;
const STAGING_MAX_AGE_MS = 6 * 60 * 60 * 1000;
const STAGING_SWEEP_INTERVAL_MS = 10 * 60 * 1000;
// uploadId is generated by the web client from safe charset; the regex is the
// server-side guarantee that it is a single safe path segment (no traversal).
const UPLOAD_ID_PATTERN = /^[A-Za-z0-9_-]{8,64}$/;

function headerString(value: unknown): string {
  return typeof value === 'string'
    ? value
    : Array.isArray(value) && typeof value[0] === 'string' ? value[0] : '';
}

/**
 * Server-side upload cap: OD_MAX_UPLOAD_MB (positive integer MB) at
 * startServer time, else the shared contracts default. This is the canonical
 * cap — GET /api/config exposes the same resolved value to the web composer
 * so a runtime env change applies to both sides without a web rebuild.
 */
export function resolveUploadMaxBytes(): number {
  const mb = Number.parseInt(process.env.OD_MAX_UPLOAD_MB ?? '', 10);
  return Number.isInteger(mb) && mb > 0 ? mb * 1024 * 1024 : PROJECT_UPLOAD_MAX_BYTES;
}

export interface RegisterProjectChunkUploadRoutesDeps
  extends RouteDeps<'db' | 'http' | 'node' | 'paths' | 'projectStore' | 'projectFiles'> {
  authorizeProjectRequest?: AuthorizeProjectRequest;
  isProjectUnmaterializedPlaceholder?: (projectId: string) => boolean;
}

interface UploadMeta {
  totalChunks: number;
  name: string;
  dir: string;
  /** Cumulative byte count per received chunk index (server-side cap tracking). */
  bytesByChunk?: Record<string, number>;
}

let lastSweepAt = 0;

function stagingDirFor(root: string, uploadId: string) {
  return path.join(root, uploadId);
}

async function readUploadMeta(
  fs: any,
  stageDir: string,
): Promise<UploadMeta | null> {
  try {
    const raw = await fs.promises.readFile(path.join(stageDir, 'meta.json'), 'utf8');
    const parsed = JSON.parse(raw);
    if (
      !Number.isInteger(parsed?.totalChunks)
      || parsed.totalChunks < 1
      || parsed.totalChunks > MAX_TOTAL_CHUNKS
      || typeof parsed?.name !== 'string'
      || typeof parsed?.dir !== 'string'
    ) return null;
    if (parsed.bytesByChunk !== undefined) {
      const sizes = parsed.bytesByChunk;
      if (typeof sizes !== 'object' || sizes === null || Array.isArray(sizes)) return null;
      for (const value of Object.values(sizes)) {
        if (typeof value !== 'number' || !Number.isInteger(value) || value < 0) return null;
      }
    }
    return parsed;
  } catch {
    return null;
  }
}

function metaTotalBytes(meta: UploadMeta): number {
  return Object.values(meta.bytesByChunk ?? {}).reduce((sum, n) => sum + (n || 0), 0);
}

async function writeUploadMeta(fs: any, stageDir: string, meta: UploadMeta) {
  await fs.promises.writeFile(path.join(stageDir, 'meta.json'), JSON.stringify(meta), 'utf8');
}

async function receivedChunkIndexes(fs: any, stageDir: string): Promise<number[]> {
  const entries = await fs.promises.readdir(stageDir);
  return entries
    .filter((e: string) => /^\d+$/.test(e))
    .map((e: string) => Number.parseInt(e, 10))
    .filter((n: number) => Number.isInteger(n) && n >= 0)
    .sort((a: number, b: number) => a - b);
}

async function sweepStaleStagingDirs(fs: any, stagingRoot: string) {
  const now = Date.now();
  if (now - lastSweepAt < STAGING_SWEEP_INTERVAL_MS) return;
  lastSweepAt = now;
  let entries: string[];
  try {
    entries = await fs.promises.readdir(stagingRoot);
  } catch {
    return;
  }
  for (const entry of entries) {
    if (!UPLOAD_ID_PATTERN.test(entry)) continue;
    const dir = path.join(stagingRoot, entry);
    try {
      const st = await fs.promises.stat(dir);
      if (now - st.mtimeMs > STAGING_MAX_AGE_MS) {
        await fs.promises.rm(dir, { recursive: true, force: true });
      }
    } catch {
      // vanished mid-sweep — fine
    }
  }
}

export function registerProjectChunkUploadRoutes(
  app: Express,
  ctx: RegisterProjectChunkUploadRoutesDeps,
) {
  const { db } = ctx;
  const { sendApiError } = ctx.http;
  const { fs } = ctx.node;
  const { PROJECTS_DIR, RUNTIME_DATA_DIR } = ctx.paths;
  const stagingRoot = path.join(RUNTIME_DATA_DIR, 'upload-staging');
  const maxUploadBytes = resolveUploadMaxBytes();
  const { getProject, getWorkspaceProject, getWorkspaceProjectByProjectId } = ctx.projectStore;
  const { readProjectFile } = ctx.projectFiles;
  const authorizeProjectRequest =
    ctx.authorizeProjectRequest ??
    createAuthorizeProjectRequest({
      db,
      getWorkspaceProject,
      getWorkspaceProjectByProjectId,
      ...(ctx.isProjectUnmaterializedPlaceholder
        ? {
            isProjectUnmaterializedPlaceholder: (_db: unknown, projectId: string) =>
              ctx.isProjectUnmaterializedPlaceholder?.(projectId) ?? false,
          }
        : {}),
      sendApiError,
    });
  const enforceWorkspaceProjectMutation = createEnforceWorkspaceProjectMutation(
    undefined,
    undefined,
    authorizeProjectRequest,
  );

  const gateWrite = async (req: any, res: any, projectId: string): Promise<boolean> =>
    enforceWorkspaceProjectMutation(
      req,
      res,
      sendApiError,
      getWorkspaceProject,
      getWorkspaceProjectByProjectId,
      db,
      projectId,
      'writeFiles',
    );

  // Chunk PUTs may outlast edge/CDN idle timeouts (Cloudflare drops a proxied
  // request unless the ORIGIN sends response bytes at least every ~100-125s on
  // non-enterprise plans). While the chunk body is still streaming in, the
  // collector writes a tiny ACK byte down the (already-open) response on an
  // interval so the edge never sees a quiet upload. The first ACK pins the
  // response at HTTP 200; the real verdict arrives as the final JSON payload:
  // {"ok":true} or {"ok":false,...} — whitespace-prefixed, still JSON.parse-able.
  const CHUNK_ACK_INTERVAL_MS = (() => {
    const ms = Number.parseInt(process.env.OD_CHUNK_ACK_MS ?? '', 10);
    return Number.isInteger(ms) && ms > 0 ? ms : 15_000;
  })();
  const CHUNK_UPLOAD_BODY_MAX_BYTES = 16 * 1024 * 1024;

  /**
   * Chunk PUT response contract (pinned via keepalive ACK):
   * - Fast path (body completes before the first ACK): normal status codes,
   *   {"ok":true} or the sendApiError envelope.
   * - ACKed path (the first ACK pins the response at HTTP 200): the verdict is
   *   carried in the final payload — {"ok":true} or {"ok":false,"error":...}.
   *   Non-web consumers MUST check the body verdict, not just the status, on
   *   chunk PUT responses that carry the x-chunk-keepalive header.
   */
  function finishChunkResponse(
    res: any,
    send: (payload: string) => void,
    ok: boolean,
    error?: string,
  ) {
    if (res.writableEnded) return;
    const payload = ok
      ? JSON.stringify({ ok: true })
      : JSON.stringify({ ok: false, ...(error ? { error } : {}) });
    send(payload);
  }

  interface CollectedChunk {
    buffer: Buffer | null;
    size: number;
    /** True once keepalive ACK bytes pinned the response at 200. */
    acked: boolean;
  }

  function collectChunkBody(req: any, res: any): Promise<CollectedChunk> {
    return new Promise((resolve) => {
      const chunks: Buffer[] = [];
      let received = 0;
      let acked = false;
      let settled = false;

      const finish = (buffer: Buffer | null) => {
        if (settled) return;
        settled = true;
        clearInterval(heartbeat);
        resolve({ buffer, size: received, acked });
      };

      const heartbeat = setInterval(() => {
        try {
          if (res.writableEnded || res.destroyed) {
            clearInterval(heartbeat);
            return;
          }
          if (!res.headersSent) {
            res.status(200);
            res.setHeader('content-type', 'text/plain');
            res.setHeader('cache-control', 'no-store');
            res.setHeader('x-chunk-keepalive', '1');
          }
          acked = true;
          res.write(' ');
        } catch {
          clearInterval(heartbeat);
        }
      }, CHUNK_ACK_INTERVAL_MS);

      res.on('close', () => finish(null));
      req.on('aborted', () => finish(null));
      req.on('error', () => finish(null));
      req.on('data', (chunk: Buffer) => {
        received += chunk.length;
        if (received > CHUNK_UPLOAD_BODY_MAX_BYTES) {
          // Over the per-chunk ceiling; stop buffering. If ACKs already
          // pinned a 200, the verdict goes out as {"ok":false} instead.
          finish(null);
          req.destroy();
          return;
        }
        chunks.push(chunk);
      });
      req.on('end', () => finish(Buffer.concat(chunks)));
    });
  }

  app.put(
    '/api/projects/:id/upload/:uploadId/chunk/:index',
    async (req, res) => {
      try {
        const { uploadId, index } = req.params;
        if (!UPLOAD_ID_PATTERN.test(uploadId)) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid upload id');
        }
        const chunkIndex = Number.parseInt(index, 10);
        if (!Number.isInteger(chunkIndex) || String(chunkIndex) !== index || chunkIndex < 0) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid chunk index');
        }
        const totalChunks = Number.parseInt(headerString(req.headers['x-total-chunks']), 10);
        if (!Number.isInteger(totalChunks) || totalChunks < 1 || totalChunks > MAX_TOTAL_CHUNKS) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid total chunks');
        }
        if (chunkIndex >= totalChunks) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'chunk index out of range');
        }
        const fileNameRaw = headerString(req.headers['x-file-name']);
        if (!fileNameRaw) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'x-file-name header required');
        }
        const dirRaw = headerString(req.headers['x-dir']);
        const uploadDir = dirRaw ? decodeURIComponent(dirRaw) : '';
        // Gate BEFORE consuming the body so rejections keep normal status
        // codes (once keepalive ACKs start, the response status is fixed).
        if (!await gateWrite(req, res, req.params.id)) {
          // Do NOT destroy here: the client may still be streaming the body,
          // and tearing down the socket would drop the 401/403 before it
          // flushes. Drain the remaining upload instead so the rejection is
          // delivered and the connection closes cleanly.
          req.on('error', () => {});
          req.resume();
          return;
        }
        const stageDir = stagingDirFor(stagingRoot, uploadId);
        await fs.promises.mkdir(stageDir, { recursive: true });
        let meta = await readUploadMeta(fs, stageDir);
        if (meta && meta.totalChunks !== totalChunks) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'total chunks does not match previous upload');
        }
        if (!meta) {
          meta = {
            totalChunks,
            name: sanitizeName(decodeURIComponent(fileNameRaw)),
            dir: uploadDir,
            bytesByChunk: {},
          };
        }

        const collected = await collectChunkBody(req, res);
        // Body fully received from here on; ACK bytes may have pinned a 200.
        try {
          if (!collected.buffer) {
            if (collected.acked) {
              finishChunkResponse(res, (payload) => res.end(payload), false, 'chunk rejected');
              return;
            }
            return sendApiError(res, 413, 'FILE_TOO_LARGE', 'chunk too large');
          }
          const body = collected.buffer;
          if (body.length === 0) {
            return sendApiError(res, 400, 'BAD_REQUEST', 'chunk body required');
          }
          // Byte budget: cumulative per-chunk sizes are tracked in meta.json so a
          // non-web client cannot stage (and later assemble) an oversized blob.
          const bytesByChunk = { ...(meta.bytesByChunk ?? {}), [String(chunkIndex)]: body.length };
          const totalBytes = Object.values(bytesByChunk).reduce((sum: number, n: number) => sum + n, 0);
          if (totalBytes > maxUploadBytes) {
            if (collected.acked) {
              finishChunkResponse(res, (payload) => res.end(payload), false, 'assembled upload exceeds the maximum size');
              return;
            }
            return sendApiError(res, 413, 'FILE_TOO_LARGE', 'assembled upload exceeds the maximum size');
          }
          await fs.promises.writeFile(path.join(stageDir, String(chunkIndex)), body);
          await writeUploadMeta(fs, stageDir, { ...meta, bytesByChunk });
          sweepStaleStagingDirs(fs, stagingRoot).catch(() => {});
          if (collected.acked && res.headersSent) {
            finishChunkResponse(res, (payload) => res.end(payload), true);
          } else {
            res.json({ ok: true });
          }
        } catch (err) {
          if (collected.acked && res.headersSent) {
            finishChunkResponse(res, (payload) => res.end(payload), false, 'chunk upload failed');
            return;
          }
          throw err;
        }
      } catch {
        sendApiError(res, 500, 'INTERNAL_ERROR', 'chunk upload failed');
      }
    },
  );

  app.post(
    '/api/projects/:id/upload/:uploadId/complete',
    async (req, res) => {
      try {
        const { uploadId } = req.params;
        if (!UPLOAD_ID_PATTERN.test(uploadId)) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid upload id');
        }
        if (!await gateWrite(req, res, req.params.id)) return;
        const stageDir = stagingDirFor(stagingRoot, uploadId);
        const meta = await readUploadMeta(fs, stageDir);
        if (!meta) {
          return sendApiError(res, 404, 'UPLOAD_NOT_FOUND', 'upload not found');
        }
        const declared = Number.isInteger(req.body?.totalChunks) ? req.body.totalChunks : null;
        if (declared !== null && declared !== meta.totalChunks) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'total chunks does not match upload');
        }
        const project = getProject(db, req.params.id);
        if (!project) {
          return sendApiError(res, 404, 'PROJECT_NOT_FOUND', 'project not found');
        }
        const received = await receivedChunkIndexes(fs, stageDir);
        if (received.length !== meta.totalChunks
          || (received.length > 0 && received[received.length - 1] !== meta.totalChunks - 1)) {
          return sendApiError(res, 400, 'INCOMPLETE_UPLOAD', 'not all chunks received');
        }
        const totalBytes = metaTotalBytes(meta);
        if (totalBytes > maxUploadBytes) {
          // Cannot ever complete within the cap — purge staging so the
          // oversized upload stops holding disk space.
          await fs.promises.rm(stageDir, { recursive: true, force: true });
          return sendApiError(res, 413, 'FILE_TOO_LARGE', 'assembled upload exceeds the maximum size');
        }
        // Streamed assembly: append each chunk file to one staging file in
        // index order so peak heap stays around a single chunk, then move the
        // assembled file into the project dir. Matches the direct /upload
        // route, which also lands files flat via its multer destination.
        const { absDir, relDir } = await ensureProjectSubdir(
          PROJECTS_DIR,
          req.params.id,
          meta.dir,
          project.metadata,
        );
        const assembled = path.join(stageDir, 'assembled');
        await fs.promises.writeFile(assembled, Buffer.alloc(0));
        for (const i of received) {
          const chunk = await fs.promises.readFile(path.join(stageDir, String(i)));
          await fs.promises.appendFile(assembled, chunk);
        }
        const target = path.join(absDir, meta.name);
        try {
          await fs.promises.rename(assembled, target);
        } catch (err: any) {
          if (err?.code !== 'EXDEV') throw err;
          // Imported projects can live on a different filesystem than staging.
          await fs.promises.copyFile(assembled, target);
        }
        const finalName = relDir ? `${relDir}/${meta.name}` : meta.name;
        if (/\.html?$/i.test(finalName)) {
          try {
            const savedFile = await readProjectFile(
              PROJECTS_DIR,
              project.id,
              finalName,
              project.metadata,
            );
            await ensureCurrentProjectFileVersion(
              PROJECTS_DIR,
              project.id,
              savedFile.name,
              savedFile.buffer.toString('utf8'),
              { source: 'manual', promptSource: 'manual' },
              project.metadata,
            );
          } catch {
            // Same best-effort posture as the direct /upload route.
          }
        }
        const st = await fs.promises.stat(target);
        await fs.promises.rm(stageDir, { recursive: true, force: true });
        /** @type {import('@open-design/contracts').UploadProjectFilesResponse} */
        const out = {
          name: finalName,
          path: finalName,
          size: st.size,
          mtime: st.mtimeMs,
          originalName: meta.name,
        };
        res.json({ files: [out] });
      } catch {
        sendApiError(res, 500, 'INTERNAL_ERROR', 'upload failed');
      }
    },
  );

  app.delete(
    '/api/projects/:id/upload/:uploadId',
    async (req, res) => {
      try {
        const { uploadId } = req.params;
        if (!UPLOAD_ID_PATTERN.test(uploadId)) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid upload id');
        }
        if (!await gateWrite(req, res, req.params.id)) return;
        await fs.promises.rm(stagingDirFor(stagingRoot, uploadId), {
          recursive: true,
          force: true,
        });
        res.json({ ok: true });
      } catch {
        sendApiError(res, 500, 'INTERNAL_ERROR', 'abort failed');
      }
    },
  );

  app.get(
    '/api/projects/:id/upload/:uploadId',
    async (req, res) => {
      try {
        const { uploadId } = req.params;
        if (!UPLOAD_ID_PATTERN.test(uploadId)) {
          return sendApiError(res, 400, 'BAD_REQUEST', 'invalid upload id');
        }
        if (!authorizeProjectRequest(req, res, req.params.id, { mode: 'write', capability: 'writeFiles' })) {
          return;
        }
        const stageDir = stagingDirFor(stagingRoot, uploadId);
        const meta = await readUploadMeta(fs, stageDir);
        if (!meta) {
          return sendApiError(res, 404, 'UPLOAD_NOT_FOUND', 'upload not found');
        }
        const received = await receivedChunkIndexes(fs, stageDir);
        res.json({ received, totalChunks: meta.totalChunks });
      } catch {
        sendApiError(res, 500, 'INTERNAL_ERROR', 'status failed');
      }
    },
  );
}
